# Generated by Django 3.0.1 on 2020-04-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1app', '0003_auto_20200419_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='django_1app.Flights')),
            ],
        ),
    ]
